// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250730122700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "telefon.jpg",
                            Name = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            Image = "laptop.jpg",
                            Name = "Laptop",
                            Url = "laptop"
                        },
                        new
                        {
                            Id = 3,
                            Image = "televizyon.jpg",
                            Name = "Televizyon",
                            Url = "televizyon"
                        },
                        new
                        {
                            Id = 4,
                            Image = "oyun_konsolu.jpg",
                            Name = "Oyun Konsolu",
                            Url = "oyun_konsolu"
                        },
                        new
                        {
                            Id = 5,
                            Image = "tablet.jpg",
                            Name = "Tablet",
                            Url = "tablet"
                        },
                        new
                        {
                            Id = 6,
                            Image = "akilli_saat.jpg",
                            Name = "Akıllı Saat",
                            Url = "akilli_saat"
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "iPhone 16, Apple'ın en yeni nesil akıllı telefonudur. Pembe renk seçeneğiyle dikkat çeker. Gelişmiş yapay zeka destekli kamera sistemi, ultra retina XDR ekran, A18 çipi ve uzun pil ömrüyle günlük kullanımı lüks hale getirir.",
                            Image = "iphone16.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "iPhone 16",
                            Price = 62000m,
                            Url = "iphone-16"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A16 Bionic çip ile güçlendirilmiş iPhone 15, enerji verimliliği ve performansı bir araya getiriyor. Kamera özellikleri, sinematik mod ve gelişmiş HDR desteği ile üst düzey çekimler yapmanıza olanak sağlar. Pembe renk ile şık bir görünüm sunar.",
                            Image = "iphone15.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "iPhone 15",
                            Price = 55000m,
                            Url = "iphone-15"
                        },
                        new
                        {
                            Id = 3,
                            Description = "iPhone 14, dayanıklı Ceramic Shield camı ve gelişmiş pil ömrüyle günlük kullanıma tam uyumludur. Mor rengi ve çift arka kamera sistemi ile estetik ve işlevselliği bir araya getirir. Crash Detection gibi hayat kurtaran özellikleriyle donatılmıştır.",
                            Image = "iphone14.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "iPhone 14",
                            Price = 43000m,
                            Url = "iphone-14"
                        },
                        new
                        {
                            Id = 4,
                            Description = "OLED ekran, güçlü A15 Bionic çip ve uzun pil ömrüyle iPhone 13, günlük kullanıcılar için mükemmel bir seçimdir. Beyaz renk seçeneği sade ve zarif bir görünüm sunar. Video ve fotoğraf çekimlerinde Smart HDR 4 teknolojisiyle üst düzey kalite sağlar.",
                            Image = "iphone13.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "iPhone 13",
                            Price = 33000m,
                            Url = "iphone-13"
                        },
                        new
                        {
                            Id = 5,
                            Description = "iPhone 12, 5G teknolojisi ve Super Retina XDR ekranı ile dikkat çeker. Mor renk ile özgün tarzını ortaya koymak isteyenler için ideal. Güçlü performansı ve MagSafe aksesuar desteği ile modern bir deneyim sunar.",
                            Image = "iphone12.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "iPhone 12",
                            Price = 25000m,
                            Url = "iphone-12"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Geniş açı kamerası, dayanıklı cam yapısı ve akıcı iOS deneyimi ile iPhone 11 kullanıcı dostudur. Beyaz rengi ile sade ve modern bir tasarım sunar. Uzun pil ömrü ve iOS güncellemeleri ile hala güçlü bir tercihtir.",
                            Image = "iphone11.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "iPhone 11",
                            Price = 20000m,
                            Url = "iphone-11"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Galaxy S24, Snapdragon 8 Gen 3 işlemcisi ve Dynamic AMOLED 2X ekranıyla üst düzey Android performansı sunar. Kamera sisteminde gece modu, 8K video ve yapay zeka destekli portre çekimleri dikkat çeker. Şık tasarımıyla göz doldurur.",
                            Image = "samsungs24.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Samsung Galaxy S24",
                            Price = 44000m,
                            Url = "samsung-galaxy-s24"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Samsung Galaxy S23, kompakt tasarımı ve güçlü donanımıyla günlük kullanıma ideal. 120Hz ekran yenileme hızı ve HDR10+ desteğiyle multimedya deneyimini üst seviyeye taşır. Gelişmiş kamera sistemi ile sosyal medya için mükemmel içerikler üretin.",
                            Image = "samsungs23.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Samsung Galaxy S23",
                            Price = 38000m,
                            Url = "samsung-galaxy-s23"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Galaxy S22, şık tasarımı ve Fiyat/performans dengesiyle öne çıkan bir modeldir. Exynos işlemci, yüksek parlaklığa sahip AMOLED ekran ve kompakt yapısı ile kullanıcı dostu bir Android deneyimi sunar. Uygun fiyatla premium his verir.",
                            Image = "samsungs22.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Samsung Galaxy S22",
                            Price = 30000m,
                            Url = "samsung-galaxy-s22"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Dell XPS 15, ultra ince tasarımı, 3.5K OLED ekranı ve 13. nesil Intel işlemcisiyle üst düzey performansı bir araya getiriyor. Hem profesyonel işler hem de multimedya için ideal bir dizüstü bilgisayar.",
                            Image = "dellxps15.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Dell XPS 15",
                            Price = 115000m,
                            Url = "dell-xps-15"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lenovo Legion Pro, güçlü ekran kartı ve yüksek tazeleme hızına sahip ekranıyla oyuncular için geliştirilmiş bir dizüstü bilgisayardır. RGB klavyesi ve üstün soğutma sistemi ile fark yaratır.",
                            Image = "lenovolegionpro.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Lenovo Legion Pro",
                            Price = 95000m,
                            Url = "lenovo-legion-pro"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Apple’ın yeni nesil M4 işlemcisine sahip MacBook Air, fan gerektirmeyen sessiz tasarımı ve uzun pil ömrü ile günlük kullanımda mükemmel performans sunar. Ultra hafif yapısıyla taşınabilirlikte lider.",
                            Image = "applemacbookairm4.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "MacBook Air M4",
                            Price = 130000m,
                            Url = "apple-macbook-air-m4"
                        },
                        new
                        {
                            Id = 13,
                            Description = "M3 çipli MacBook Air, Apple ekosistemiyle kusursuz uyum içinde çalışır. Öğrenciler, içerik üreticileri ve günlük kullanıcılar için yüksek performans ve batarya verimliliği sunar.",
                            Image = "applemacbookairm3.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "MacBook Air M3",
                            Price = 118000m,
                            Url = "apple-macbook-air-m3"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Apple’ın ikonik tasarımıyla birleşen M2 işlemcisi sayesinde MacBook Air M2, verimli işlem gücü ve üstün ekran kalitesi ile tanınır. Profesyoneller için ideal bir seçenek.",
                            Image = "applemacbookairm2.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "MacBook Air M2",
                            Price = 99000m,
                            Url = "apple-macbook-air-m2"
                        },
                        new
                        {
                            Id = 15,
                            Description = "MSI Katana GF66, yüksek performanslı NVIDIA RTX ekran kartı, hızlı SSD depolama ve şık tasarımıyla oyun tutkunları için özel olarak üretilmiş bir dizüstü bilgisayardır.",
                            Image = "msikatana.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "MSI Katana GF66",
                            Price = 87000m,
                            Url = "msi-katana-gf66"
                        },
                        new
                        {
                            Id = 16,
                            Description = "HP Victus 16, oyun ve günlük kullanım için dengeli performans sunar. AMD ve Intel varyantlarıyla farklı ihtiyaçlara hitap ederken tasarımıyla da dikkat çeker.",
                            Image = "hpvictus16.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "HP Victus 16",
                            Price = 78000m,
                            Url = "hp-victus-16"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Acer Nitro V5, geniş ekranı, yüksek performanslı donanımı ve etkileyici soğutma sistemiyle özellikle oyuncular ve güç kullanıcıları için geliştirilmiş bir laptop modelidir.",
                            Image = "acernitrov5.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Acer Nitro V5",
                            Price = 74000m,
                            Url = "acer-nitro-v5"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Samsung'un QLED teknolojisi ile donatılmış bu 55 inçlik televizyon, kristal netliğinde görüntü kalitesi ve HDR desteği ile ev sinema keyfini bir üst seviyeye taşıyor. Akıllı TV özellikleri, yerleşik uygulamalar ve sesli kontrol desteği ile zengin bir kullanıcı deneyimi sunar.",
                            Image = "samsungqledsmart4k.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Samsung QLED Smart 4K 55",
                            Price = 32500m,
                            Url = "samsung-qled-smart-4k-55"
                        },
                        new
                        {
                            Id = 19,
                            Description = "TCL'in yüksek çözünürlüklü 50 inç Android TV’si, geniş ekran deneyimi, Google TV entegrasyonu ve Dolby Vision teknolojisi ile uygun fiyatlı bir premium seçenek sunar. Minimalist tasarımıyla her odaya uyum sağlar.",
                            Image = "tcl50.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "TCL 50 4K Ultra HD Android TV",
                            Price = 18900m,
                            Url = "tcl-50-4k-ultra-hd-android-tv"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Philips Ambilight özelliği ile ortam aydınlatmasını ekranla senkronize eden bu televizyon, sinema keyfini eve taşıyor. 4K çözünürlük, Dolby Atmos desteği ve Android işletim sistemiyle etkileyici bir performans sunar.",
                            Image = "Philipsambilight.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Philips Ambilight 50 Smart TV",
                            Price = 27900m,
                            Url = "philips-ambilight-50-smart-tv"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Sony Bravia XR teknolojisi ile görüntüleri yapay zeka desteğiyle işleyerek olağanüstü kontrast ve renk doğruluğu sunar. OLED paneli, derin siyahlar ve etkileyici detaylarla sinema keyfini yeniden tanımlar. Google TV ile zengin uygulama desteği de cabası.",
                            Image = "sonybravia.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Sony Bravia XR OLED 55",
                            Price = 48500m,
                            Url = "sony-bravia-xr-oled-55"
                        },
                        new
                        {
                            Id = 22,
                            Description = "LG'nin OLED Evo teknolojisiyle donatılmış bu model, olağanüstü görüntü kalitesi ve canlı renklerle dikkat çeker. WebOS işletim sistemi, Magic Remote ve Dolby Vision IQ ile akıllı deneyimi zenginleştirir.",
                            Image = "oledevo4.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "OLED Evo 4K LG 55",
                            Price = 44900m,
                            Url = "oled-evo-4k-lg-55"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Nintendo Switch OLED modeli, canlı renkler ve gelişmiş taşınabilirlik sunar. 7 inç OLED ekran, daha geniş ayarlanabilir stand, gelişmiş ses deneyimi ve 64 GB dahili depolama ile oyun keyfini yeniden tanımlıyor.",
                            Image = "nintendoswitcholed.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Nintendo Switch OLED",
                            Price = 13500m,
                            Url = "nintendo-switch-oled"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Microsoft'un en güçlü konsolu olan Xbox Series X, 1TB SSD, 4K çözünürlükte 120 FPS oyun desteği ve ultra hızlı yükleme süreleri ile üst düzey performans sunar.",
                            Image = "xboxseriesx.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Xbox Series X",
                            Price = 22000m,
                            Url = "xbox-series-x"
                        },
                        new
                        {
                            Id = 25,
                            Description = "PlayStation 5 Slim, yüksek performans ve daha ince tasarımı bir araya getiriyor. 4K 120Hz desteği, gelişmiş DualSense kontrolleri ve geniş oyun kütüphanesi ile sizi oyun dünyasına taşır.",
                            Image = "ps5slim.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "PlayStation 5 Slim",
                            Price = 30000m,
                            Url = "playstation-5-slim"
                        },
                        new
                        {
                            Id = 26,
                            Description = "PlayStation Portal, PS5 konsolunuzdaki oyunları uzaktan oynamanızı sağlayan taşınabilir bir cihazdır. 8 inç LCD ekranı ve DualSense entegre kontrolleri ile mobil oyun deneyimi sunar.",
                            Image = "playstationportal.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "PlayStation Portal",
                            Price = 15000m,
                            Url = "playstation-portal"
                        },
                        new
                        {
                            Id = 27,
                            Description = "PlayStation 4 Slim, kompakt tasarımı ve güçlü performansı ile oyun deneyimini ekonomik şekilde yaşamak isteyenler için ideal bir konsoldur.",
                            Image = "playstation4.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "PlayStation 4 Slim",
                            Price = 21000m,
                            Url = "playstation-4-slim"
                        },
                        new
                        {
                            Id = 28,
                            Description = "120 Hz ekran yenileme hızı, Snapdragon işlemcisi ve hafif tasarımıyla yüksek performanslı bir tablet deneyimi sunar.",
                            Image = "huaweimatpad11.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Huawei MatePad 11",
                            Price = 10999m,
                            Url = "huawei-matepad-11"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Geniş 12.7 inç ekranı ve yüksek çözünürlüğü ile film izleme ve çizim yapma keyfini doruklara çıkarır.",
                            Image = "lenovotab12pro.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Lenovo Tab 12 Pro",
                            Price = 12999m,
                            Url = "lenovo-tab-12-pro"
                        },
                        new
                        {
                            Id = 30,
                            Description = "2880x1800 çözünürlüklü ekranı, Snapdragon 870 işlemcisi ve Dolby Atmos destekli hoparlörleriyle multimedya için ideal.",
                            Image = "xiaomipad6.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Xiaomi Pad 6",
                            Price = 11499m,
                            Url = "xiaomi-pad-6"
                        },
                        new
                        {
                            Id = 31,
                            Description = "14.6 inç Dynamic AMOLED ekran, IP68 suya dayanıklılık ve S Pen desteği ile profesyonel seviyede bir Android tablet.",
                            Image = "samsunggalaxytabs9.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Samsung Galaxy Tab S9 Ultra",
                            Price = 32999m,
                            Url = "samsung-galaxy-tab-s9-ultra"
                        },
                        new
                        {
                            Id = 32,
                            Description = "M4 çipi, Liquid Retina XDR ekranı ve Apple Pencil Pro desteği ile içerik üreticileri ve profesyoneller için en güçlü iPad.",
                            Image = "appleipadpro.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Apple iPad Pro",
                            Price = 42000m,
                            Url = "apple-ipad-pro"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Ultra ince tasarımı ve gelişmiş AMOLED ekranı ile dikkat çeken Amazfit GTS 4, sağlık takibi ve spor aktiviteleri için ideal.",
                            Image = "amazfitgt6.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Amazfit GTS 4",
                            Price = 4799m,
                            Url = "amazfit-gts-4"
                        },
                        new
                        {
                            Id = 34,
                            Description = "1.43 inç AMOLED ekranı, 117 spor modu ve uzun pil ömrü ile Xiaomi Watch S1 Active günlük kullanım için mükemmel bir akıllı saat.",
                            Image = "xiaomi-watch-s1-active-siyah.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Xiaomi Watch S1 Active",
                            Price = 3899m,
                            Url = "xiaomi-watch-s1-active"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Şık tasarımı ve uzun pil ömrüyle dikkat çeken Huawei Watch GT 4, sağlık takibi ve spor özelliklerini bir arada sunar.",
                            Image = "huaweiwatchgt6.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Huawei Watch GT 4",
                            Price = 5999m,
                            Url = "huawei-watch-gt-4"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Samsung’un son nesil akıllı saati Watch 6, güçlü donanımı ve kapsamlı sağlık özellikleriyle öne çıkıyor.",
                            Image = "samsunggalaxywatch6.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Samsung Galaxy Watch 6",
                            Price = 7799m,
                            Url = "samsung-galaxy-watch-6"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Apple’ın en yeni akıllı saati Series 9, güçlü işlemcisi ve gelişmiş sağlık özellikleriyle iPhone kullanıcıları için vazgeçilmez.",
                            Image = "applewatchseries.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            Name = "Apple Watch Series 9",
                            Price = 17499m,
                            Url = "apple-watch-series-9"
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 6
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("StoreApp.Data.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StoreApp.Data.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "İhtiyacını şimdi al, 6 taksitle öde!",
                            Image = "kampanya1.jpg",
                            IsActive = true,
                            Link = "/kampanya/1",
                            SubTitle = "Son Gün 21 Temmuz",
                            Title = "Peşin Fiyata 6 Taksit",
                            Url = "kampanya-1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tüm ürünlerde kargo ücretsiz!",
                            Image = "kampanya2.jpg",
                            IsActive = true,
                            Link = "/kampanya/2",
                            SubTitle = "Her üründe geçerli",
                            Title = "Ücretsiz Kargo",
                            Url = "kampanya-2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "İninal Visa ile 1.500 TL’ye varan indirim!",
                            Image = "kampanya3.png",
                            IsActive = true,
                            Link = "/kampanya/3",
                            SubTitle = "Ekstra indirim fırsatı",
                            Title = "1.500 TL İndirim",
                            Url = "kampanya-3"
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Entities.SiteSocialAddressSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSocialAddressSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacebookUrl = "https://facebook.com/yourpage",
                            InstagramUrl = "https://instagram.com/yourpage",
                            PhoneNumber = "0212 212 12 12",
                            TwitterUrl = "https://twitter.com/yourpage",
                            YoutubeUrl = "https://youtube.com/yourpage"
                        });
                });

            modelBuilder.Entity("StoreApp.Data.Entities.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Slides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "banner1.jpg",
                            IsActive = true,
                            Link = "/kampanya1",
                            Order = 1,
                            Title = "Kampanya 1"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "banner2.jpg",
                            IsActive = true,
                            Link = "/kampanya2",
                            Order = 2,
                            Title = "Kampanya 2"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "banner3.jpg",
                            IsActive = true,
                            Link = "/kampanya3",
                            Order = 3,
                            Title = "Kampanya 3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StoreApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StoreApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StoreApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Order", b =>
                {
                    b.HasOne("StoreApp.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApp.Data.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.OrderItem", b =>
                {
                    b.HasOne("StoreApp.Data.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApp.Data.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.ProductCategory", b =>
                {
                    b.HasOne("StoreApp.Data.Concrete.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApp.Data.Concrete.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreApp.Data.Entities.Address", b =>
                {
                    b.HasOne("StoreApp.Data.Entities.AppUser", "AppUser")
                        .WithMany("Addresses")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("StoreApp.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
